# Generated by Django 4.2.19 on 2025-04-28 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_bill_time_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 33, 13, 664468)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 33, 13, 665289)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 33, 13, 665406)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 33, 13, 664766)),
        ),
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 33, 13, 664301)),
        ),
    ]
