# Generated by Django 4.2.19 on 2025-06-02 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 17, 37, 18, 259411)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 17, 37, 18, 258870)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 17, 37, 18, 258706)),
        ),
    ]
