# Generated by Django 4.2.19 on 2025-04-28 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_bill_time_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='describe',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 34, 43, 850550)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 34, 43, 851344)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 34, 43, 851463)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 34, 43, 850819)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 34, 43, 850392)),
        ),
    ]
